theme: jekyll-theme-minimal
baseurl: trop.io
title: Trop.io by Trophic
email: Oh look! Use this E Mail to talk to me!
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
